tartley/colorama

README.rst

After all, this is **color**ama. :smile: 
Preview at https://github.com/msabramo/colorama-1/blob/patch-1/README.rst

README.rst: Add color syntax highlighting

---

setup.py

The GitHub URL is more useful than the PyPI URL, because this data is most often seen on PyPI.

setup.py: Change url to github

---

colorama/__init__.py
colorama/initialise.py
demos/demo.sh
demos/demo08.py

This enables you to handle the stdout replacement with a with statement rather than manually keeping track of it... for example:
with colorama_text():
print Fore.GREEN, 'text is green'
print Fore.RESET, 'text is back to normal'
print 'text is back to stdout'

Add context manager for colorama

---

README.rst

A start towards addressing https://github.com/tartley/colorama/issues/71
Most of the diffs are contentless whitespace faffing - I like to view things in an 80 char terminal. My apologies.
The only substantive changes are:
* I removed my own email address as a suggested project 'contact' (because I no longer actively contribute these days)
* I removed contributor Jesse's email address from this public README. (Sorry Jesse!)
* I added the word 'contact' to the link to the colorama discussion group, so that people doing 'find in page' for 'contact' will find it.

Issue71 readme tidy

---

colorama/win32.py

Fixes #95.
Tests fail locally for me even without these changes and I couldn't find any tests for `winapi_test()`, so I'm not sure if this PR is complete.  Let me know if anything is missing, I'll follow up!

Enables color on stderr when only stdout is redirected to file

---

.travis.yml
README.rst
colorama/tests/ansi_test.py
colorama/tests/ansitowin32_test.py
colorama/tests/initialise_test.py
colorama/tests/winterm_test.py
setup.py
tox.ini

Fixes #153, which so far has one 👍  and no objections.
Also add `python_requires` to setup.py to help pip.

Drop EOL Python 2.5, 2.6, 3.1, 3.2 and 3.3

---

colorama/ansitowin32.py

Fixes #107 
Replaces the abandoned #108

Add support for PyCharm

---

README.rst
setup.py

For details on the new PyPI, see the blog post:
https://pythoninsider.blogspot.ca/2018/04/new-pypi-launched-legacy-pypi-shutting.html

Update all pypi.python.org URLs to pypi.org

---

colorama/tests/ansitowin32_test.py

The `io` module is available on all supported Pythons. It was added in version 2.6. The fallback is never used. For additional details on the module, see:
https://docs.python.org/3/library/io.html
https://docs.python.org/2/library/io.html

Remove unused "except ImportError"

---

.gitignore

The directories are auto-generated during the command "tox" and should
not be committed to version control.

Add generated testing directories to .gitignore

---

colorama/ansitowin32.py
colorama/tests/initialise_test.py
colorama/tests/isatty_test.py
colorama/tests/utils.py

Hi.
This is related to a comment I left some days ago: https://github.com/tartley/colorama/pull/163#issuecomment-388280675
I think this is quite important to **only** wrap `stdout` and `stderr` on Pycharm, rather than **any** stream. Think for example of a logging module which relies on `colorama` to wrap arbitrary handler's stream. :wink:

Prevent file stream from being incorrectly wrapped on Pycharm

---

.gitignore
tox.ini

Running the command `tox` now tests in the same way as Travis CI and as
recommended in the docs. Makes it simpler to recreate an identical test
environment locally.

Use the recommended test command in tox.ini

---

colorama/win32.py

The fix is to simply not cache the std handles returned by `GetStdHandle`
This happens in Pytest on at least Python 3.5 and 3.6.
Please check https://github.com/pytest-dev/pytest/issues/2465 for more information about this before merging.

Don't break due to our handles getting closed by FD redirection

---

colorama/ansitowin32.py

See #197 for extended discussion.

Prevent exponential number of calls while accessing "closed" / "isatty" (#196)

---

README.rst

`\033[30m` is the sequence for black and I was pretty worried because I assumed it would reset but my text just disappeared (I use white text on black bg so black text disappears)
`\033[39m` is the code for reset that should be used here.

[FIX] Fix example with ANSI sequence

---

.travis.yml
README.rst
setup.py
tox.ini

Also test on Python 3.8 beta, due out in October.
* https://www.python.org/dev/peps/pep-0569/

Add support for Python 3.7 and 3.8, drop EOL 3.4

---

Makefile

Type 'make' or 'make help' to see the magic.
$ make
help    Display help for documented make targets.
clean   Remove build artifacts and .pyc files
sdist   Build an sdist file
upload  Upload an sdist file
test    Run tests
tags    Create tags file
This usage info is culled from each target's double hash (##) comments in the Makefile.

Self-documenting makefile.

---

.travis.yml
colorama/tests/initialise_test.py

Travis-CI has added support for ARM64. Added ARM64 jobs in Travis-CI for python v3.7.
As per the discussion https://github.com/tartley/colorama/issues/248

Added arm64 jobs in Travis-CI

---

README.rst
colorama/tests/ansitowin32_test.py
colorama/tests/initialise_test.py
colorama/tests/utils.py
colorama/tests/winterm_test.py
requirements-dev.txt
tox.ini

Python has a built-in mocking support since 3.3.  Use the built-in
module to avoid the dependency on external mock whenever possible,
and fall back to it on older versions of Python.

Use built-in unittest.mock when available

---

README.rst

Demote headings to make them smaller in rendered doc.
Spellcheck.
Merge 'dependencies' into 'developement'.
Abbreviate the links section text.

Readme tweaks

---

colorama/tests/ansitowin32_test.py

These were failing for me when run on Windows.
But passed on Linux.
It wasn't immediately clear to me whether it was the failing
test that was wrong, or the implementation. But I recall this
section of code undergoing much-discussed changes a
year or more ago, so I'm loathe to mess with it without
understanding the context. Presumably if the code was
wrong, users would be complaining.
So I fixed the tests, and now they should pass everywhere
(I tried on Linux and Windows.)

Make ansitowin32 tests pass on all OS

---

.gitignore
Makefile
README.rst
bootstrap.ps1
build.ps1
clean.ps1
release.ps1
test-release
test-release.ps1
test.ps1

Add a new 'test-release' script and makefile target
Running the script sends the already built package to
test pypi, then uses pip to download and install it from
there, and does a minimal invocation of the installed
package. If the package has not been built correctly,
this might detect some errors before we send it to
the real pypi.

Script to test releases

---

README-hacking.md

The nose project has ceased development. The last commit is from Mar 3,
2016. From their docs page:
https://nose.readthedocs.io/
> Note to Users
>
> Nose has been in maintenance mode for the past several years and will
> likely cease without a new person/team to take over maintainership.
> New projects should consider using Nose2, py.test, or just plain
> unittest/unittest2.

Remove discussion of unmaintained nose for running tests

---

setup.py

Prevents future regression of #291 following 688f6cc

Use ASCII decoding explicitly in setup.py

---

README.rst

This makes the behavior described at https://github.com/tartley/colorama/issues/209#issuecomment-465119302 explicit.

Note that escapes are stripped out for redirected outputs.

---

colorama/tests/initialise_test.py
colorama/tests/utils.py

Removing unused imports exposed redirected_output() as an unused
function. It too has been removed.

Remove unused test imports and utils

---

README.rst
setup.py
tox.ini

```console
$ tox -e py310
GLOB sdist-make: /private/tmp/colorama/setup.py
py310 create: /private/tmp/colorama/.tox/py310
py310 inst: /private/tmp/colorama/.tox/.tmp/package/1/colorama-0.4.5rc0.zip
py310 testmon: setting TESTMON_DATAFILE=/private/tmp/colorama/.tox/py310/.testmondata
py310 installed: colorama @ file:///private/tmp/colorama/.tox/.tmp/package/1/colorama-0.4.5rc0.zip
py310 run-test-pre: PYTHONHASHSEED='2568120525'
py310 run-test: commands[0] | python -m unittest discover -p '*_test.py'
.........................................sss....s
----------------------------------------------------------------------
Ran 49 tests in 0.038s
OK (skipped=4)
______________________________________________________ summary _______________________________________________________
py310: commands …
```

Add support for Python 3.10

---

CHANGELOG.rst
colorama/ansitowin32.py

Closes #86.
The popular python linter `pylint` has updated its pickler module from the `stdlib` `pickle` to the widely used `dill` package. However, users have run into issues with this as `colorama` apparently does not support pickling by `dill`. One user already identified this issue 6 years ago, but a fix was never submitted.
The following fixes the issue and passes all tests. We would appreciate if this could get merged as `pylint` is somewhat unable to return to `pickle` but we also don't want to stop supporting `colorama`. 
As for a test, I didn't want to add `dill` as a test dependency, but that would be the easiest way to test this I think. Just trying to pickle `StreamWrapper` with `dill` would fail without the code in this PR.

Add methods to ``StreamWrapper`` to allow better pickling

---

.github/workflows/test.yml

`pypyX` is deprecated and is not available in newer images:
https://github.com/actions/setup-python/issues/244#issuecomment-925966022
Instead explicitly specify the version:
https://github.com/actions/setup-python#specifying-a-pypy-version

CI: Replace deprecated pypyX with pypy-X.Y

---

README.rst
colorama/ansitowin32.py
colorama/tests/ansitowin32_test.py

A library we use throws this annoying error when it's called in under certain conditions. It's probably doing something wrong, but I think `colorama` should be more resilient to this particular bad state. I've attached the script that demonstrates the error. I've tried to write a test for this, but the best I can to do honestly test the functionality is to spin up a new Python in a subprocess that calls `colorama`,  this seems awkward and was difficult to make portable. If it's your desire I'll do it though.
```
from __future__ import print_function
import codecs
import sys
from colorama import init
init()
sys.stdout = codecs.getwriter("utf-8")(sys.stdout.detach())
print("foo", sys.stdout)
```
Before and after the fix:
Rejected test attempt:
```
def testDetachAfterInitDoesntThrow(self): …
```

Atexit fix

---

README.rst
colorama/__init__.py
colorama/ansitowin32.py
colorama/initialise.py
colorama/tests/initialise_test.py
colorama/winterm.py
demos/demo01.py
demos/demo02.py
demos/demo06.py
demos/demo07.py

As discussed in https://github.com/tartley/colorama/pull/139
Re: the bugs you collected:
> * [Guard against multiple calls to init(). #236](https://github.com/tartley/colorama/pull/236)  Guard against multiple calls to init()
> * [Prevent user from wrapping already wrapped streams #201](https://github.com/tartley/colorama/pull/201) Prevent user from wrapping already-wrapped streams
`just_fix_windows_console()` is a no-op if run repeatedly, or if run after someone else has called `init`.
> * [Support possibility to wrap either stdout or stderr #257](https://github.com/tartley/colorama/pull/257) Support possibility to wrap either stdout or stderr (for binary stdout)
`just_fix_windows_console` only touches streams that are pointing to a Windows console. So I guess in theory it would still …

Add colorama.just_fix_windows_console()

---

colorama/winterm.py

This fixes an issue present in `colorama-0.4.6` when run in `python-2.7` on `msys` or `git-bash` terminals (such as `mintty`).  In such a case the following error has been observed
```
File "C:\...\.venv\lib\site-packages\click\core.py", line 950, in show_help
echo(ctx.get_help(), color=ctx.color)
File "C:\...\.venv\lib\site-packages\click\utils.py", line 267, in echo
file = auto_wrap_for_ansi(file)
File "C:\...\.venv\lib\site-packages\click\_compat.py", line 704, in auto_wrap_for_ansi
ansi_wrapper = colorama.AnsiToWin32(stream, strip=strip)
File "C:\...\.venv\lib\site-packages\colorama\ansitowin32.py", line 101, in __init__
system_has_native_ansi = not on_windows or enable_vt_processing(fd)
File "C:\...\.venv\lib\site-packages\colorama\winterm.py", line 183, in enable_vt_processing …
```

Support python-2.7 in enable_vt_processing

---

.github/workflows/test.yml
README.rst
pyproject.toml
tox.ini

Fixes https://github.com/tartley/colorama/issues/360.
Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk).
[![image](https://user-images.githubusercontent.com/1324225/198233993-5b79523b-370f-4316-a4be-9403c8209068.png)](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)

Add support for Python 3.11

---

.github/workflows/test.yml
README.rst
colorama/ansi.py
colorama/ansitowin32.py
colorama/initialise.py
colorama/tests/ansitowin32_test.py
colorama/tests/initialise_test.py
colorama/tests/winterm_test.py
colorama/winterm.py
demos/demo01.py
demos/demo02.py
demos/demo03.py
demos/demo04.py
demos/demo05.py
demos/demo06.py
demos/demo07.py
demos/demo08.py
pyproject.toml
requirements-dev.txt
tox.ini

Follow on from https://github.com/tartley/colorama/pull/403#discussion_r2190489805
Python 2.7-3.8 are EOL:
https://devguide.python.org/versions/
2.7 and 3.7 are also no longer available on GitHub Actions causing the CI to fail. This PR also takes the opportunity to drop EOL 3.8.
This allows future improvements such as f-strings.

Drop support for EOL Python 2.7-3.8
